### ISSUE TITLE
Does it make sense to create the resource eagerly?

### ISSUE THREAD

**Issue by Hypnosphi** [kentcdodds/concurrent-react#5]
You're creating the resource inside `startTransition` callback:

```js
startTransition(() => {
  setPokemonResource(getPokemonResource(newPokemonName))
})
```

Maybe it would be better to create the resource synchronously, and only update the state inside `startTransition`? That way, the requests will be sent as early as possible:

```js
const newPokemonResource = getPokemonResource(newPokemonName)
startTransition(() => {
  setPokemonResource(newPokemonResource)
})
```

**Comment by kentcdodds** [comment]
Hi @Hypnosphi,

That might be a good idea. I'm not sure whether this is something that will change in the future, but right now `startTransition` appears to be synchronous. You can tell that by the logs here: https://codesandbox.io/s/jolly-merkle-3v7g7?fontsize=14&hidenavigation=1&initialpath=%2Fisolated%2Fexercises-final%2F04&module=%2Fsrc%2Fexercises-final%2F04.js&theme=dark

Thanks! :)
